name: RDP Windows 2022 via Avica Lite

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
 
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://github.com/arifkembiri/RDP-Windows-2022-via-Avica/raw/refs/heads/main/Downloads-lite.bat" -OutFile "Downloads.bat"
          cmd /c Downloads-lite.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
